version: "3.9"

services:
  nginx:
    image: nginx
    ports:
      - "8787:80"
    volumes:
      - ./laravelapp:/var/www/html/laravelapp
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - fpm

  fpm:
    build: ./docker/
    volumes:
      - ./laravelapp:/var/www/html/laravelapp

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3310:3306
    environment:
      MYSQL_DATABASE: laravelapp
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - laravelappdb:/var/lib/mysql
    restart: always

volumes:
  laravelappdb: